# for what versions are available, see:
# https://github.com/travis-ci/travis-cookbooks/blob/master/ci_environment/perlbrew/attributes/multi.rb
sudo: false
addons:
  apt:
    packages:
      - aspell
language: perl
perl:
    #- dev
    - "blead"
    #- stable
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install YAML
  - cpan-install ExtUtils::MakeMaker~6.68 --deps
  - cpan-install --coverage
script:
  - perl Makefile.PL
  - make
  - cpanm Dist::Zilla::Plugin::PromptIfStale
  - dzil stale --all | cpanm
  - RELEASE_TESTING=1 prove -b -r -s -j$((SYSTEM_CORES + 1)) $(test-dirs)
